server:
  port: 8080

spring:
  application:
    name: boilerplate-api

  datasource:
    url: jdbc:postgresql://localhost:5432/boilerplate_prod
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate   # ❗ production sebaiknya validate / none
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: auth-service-prod
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

jwt:
  secret: "my_dev_secret_key_32_chars_long_____"
  expiration: 86400000 # 1 day

swagger:
  enabled: true

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: WARN
